### ISSUE TITLE
Windows Pycrypto Build Issues/Not Supported

### ISSUE THREAD

**Issue by btotharye** [CiscoUcs/intersight-python#25]
So it appears from https://github.com/dlitz/pycrypto/issues/238 that pycrypto isn't really being maintained anymore and it appears that https://github.com/Legrandin/pycryptodome is the newer maintained version.

Anyone trying to use this SDK on windows is going to run into multiple issues with the VC build process due to pycrypto.

Should we update this to use pycryptodome?  I can put a PR in for it if need be.

Thanks

**Comment by dsoper2** [comment]
pycryptodome is in internal test now and will be changed to when QA is complete

**Comment by dsoper2** [comment]
Pycryptodome is now used instread of pycrypto
